### ISSUE TITLE
checklist to create enhanced bottomless pit

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#796]
- [ ] Get code working to make BTS pit or pit that doesn't require skybox to be part of the map and not a skybox... (this will allow paint, lasers, ect to fall into the pit and the player to look up without seeing no draw and also PERFECT light transition
- [ ] make sure bts pit is deep enough for paint to fall in before fading into fog, make template from bts pit for texturing pit wall and floor parts with skybox texture for next type of pit...
- [ ] texture open pit walls with skybox below square beams and panels etc and generate a skybox in map somewhere, this will make the walls below the square beams and frames invisible and show through into the skybox, make sure skybox wall is at the back of the voxel that the square beams and wall occupy to get pillars in skybox textured wall pit in test chamber, this way horizontal pillars would be easier to generate in pit in map, also skybox behind square beams will allow portal fires to pass through them and appear to not hit anything...
- [ ] make code to generate test chambers, vac tubes, instances etc in skybox and in the pit in the map the player can fall into supports for pillars, along with vac tubes, wires etc...
- [ ] some item similar to the cutout tile that will allow generation of holes in ceilings and walls, or make open walls and ceilings for some pits, and make portal fires not be seen when they hit the skybox texture because it's far enough back to create the illusion of a hole in the ceiling with objects like vactubes, wires, lights, layers of sq beams, etc between the skybox texture and square beams...
- [ ] proper coding to generate support  pillars in pit for piston platforms etc and for the hole in the ceiling skybox item, coding to generate a path of random vac tubes (even in skybox and connected to map somehow) if a cube dropper is placed right in the middle of where the hole will be...

@TeamSpen210 and @BenVlodgi

if you can pull this off, you will have much more realistic pit generation...

**Comment by ellingtonvengaboysmuseum** [comment]
@TeamSpen210 

also is there a way to pin this post to the top so we won't loose it in the myriad of new posts...

**Comment by TeamSpen210** [comment]
No, there's not. Actually I have some alternate plans, which might allow making bottomless pits and skybox directly around the main map, just like in Valve's maps.

**Comment by ellingtonvengaboysmuseum** [comment]
@TeamSpen210 - how do you plan to combine the skybox and pit into the map? this sounds tricky, you will have to texture the outside of the test chamber instances for this...

and doing this with the underground test chambers will be hard...

**Comment by Luke18033** [comment]
> No, there's not. Actually I have some alternate plans, which might allow making bottomless pits and skybox directly around the main map, just like in Valve's maps.

Out of curiosity, was this referring to the tiling system?

**Comment by TeamSpen210** [comment]
It would be yeah.

**Comment by Konclan** [comment]
#3891

**Comment by ApetureScience-Helpsystem** [comment]
i am waiting
